name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: install cfssl
      run: go install github.com/cloudflare/cfssl/cmd/cfssl@v1.4.1

    - name: install cfssljson
      run: go install github.com/cloudflare/cfssl/cmd/cfssljson@v1.4.1

    - name: Setup CA for TLS
      run: make gencert

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
